# Generated by Django 3.0.2 on 2020-01-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='etc',
            field=models.TextField(default='hi'),
        ),
    ]
