# Generated by Django 3.0.2 on 2020-01-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todos2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todos',
        ),
    ]
