# Generated by Django 3.0.2 on 2020-01-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_delete_todos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos2',
            new_name='Todos',
        ),
    ]
